version: "3.8"

services:

  # Base de datos del microservicio de limpieza
  db-limpieza:
    image: mysql:8.0
    container_name: db-limpieza
    environment:
      MYSQL_DATABASE: db_limpieza
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"  # 3308 para no colisionar con db-pagos (3307)
    networks:
      - homerent-net

  # RabbitMQ (compartido con ms-pagos)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - homerent-net

  # Eureka Server
  ms-eureka:
    build: ./MS-Eureka
    container_name: ms-eureka
    ports:
      - "8761:8761"
    networks:
      - homerent-net

  # Microservicio de Limpieza
  ms-limpieza:
    build: ./ms-limpieza
    container_name: ms-limpieza
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-limpieza:3306/db_limpieza
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ms-eureka:8761/eureka/
    depends_on:
      - db-limpieza
      - rabbitmq
      - ms-eureka
    networks:
      - homerent-net

networks:
  homerent-net:
    driver: bridge

